nsPrefix: onap
pullPolicy: IfNotPresent
nodePortPrefix: 302
image:
  readiness: oomk8s/readiness-check:1.0.1
  dmaap: attos/dmaap:latest
  kafka: wurstmeister/kafka:latest
  zookeeper: wurstmeister/zookeeper:latest
