nsPrefix: onap
pullPolicy: IfNotPresent
nodePortPrefix: 302
mysqlPassword: strong_pitchou
image:
  readiness: oomk8s/readiness-check:1.0.1
  clampImage: nexus3.onap.org:10001/onap/clamp
  clampVersion: v1.1.0
  mariadbImage: nexus3.onap.org:10001/mariadb
  mariadbVersion: 10.1.11
