#{{ if not .Values.disableSdncSdncDgbuilder }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sdnc-dgbuilder
  namespace: "{{ .Values.nsPrefix }}-sdnc"
spec:
  selector:
    matchLabels:
      app: sdnc-dgbuilder
  template:
    metadata:
      labels:
        app: sdnc-dgbuilder
      name: sdnc-dgbuilder
#      annotations:
#        pod.beta.kubernetes.io/init-containers: '[
#          {
#              "args": [
#                  "--container-name",
#                  "sdnc-db-container",
#                  "--container-name",
#                  "sdnc-controller-container"
#              ],
#              "command": [
#                  "/root/ready.py"
#              ],
#              "env": [
#                  {
#                      "name": "NAMESPACE",
#                      "valueFrom": {
#                          "fieldRef": {
#                              "apiVersion": "v1",
#                              "fieldPath": "metadata.namespace"
#                          }
#                      }
#                  }
#              ],
#              "image": "{{ .Values.image.readiness }}",
#              "imagePullPolicy": "{{ .Values.pullPolicy }}",
#              "name": "sdnc-dgbuilder-readiness"
#          }
#          ]'
    spec:
      initContainers:
      - name: sdnc-dgbuilder-readiness
        command: ['sh', '-c', '/root/ready.py --container-name sdnc-db-container --container-name sdnc-controller-container']
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: {{ .Values.image.readiness }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        volumeMounts:
        - mountPath: /root/.kube/config
          name: kubeconf
      containers:
      - command:
        - /bin/bash
        - -c
        - npm config set proxy --HTTP-PROXY-GOES-HERE-- && npm config set https-proxy --HTTPS-PROXY-GOES-HERE-- && cd /opt/onap/sdnc/dgbuilder/ && ./start.sh sdnc1.0 && wait/
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: openECOMP1.0
        - name: SDNC_CONFIG_DIR
          value: /opt/onap/sdnc/data/properties
        image: {{ .Values.image.dgbuilderSdnc }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        name: sdnc-dgbuilder-container
        ports:
        - containerPort: 3100
        readinessProbe:
          tcpSocket:
            port: 3100
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: kubeconf
        hostPath:
          path: /root/.kube/config
      imagePullSecrets:
      - name: "{{ .Values.nsPrefix }}-docker-registry-key"
#{{ end }}
