nsPrefix: onap
pullPolicy: IfNotPresent
nodePortPrefix: 302
image:
  readiness: oomk8s/readiness-check
  readinessVersion: 1.0.1
  postgresImage: nexus3.onap.org:10001/onap/refrepo/postgres
  postgresVersion: latest
  refrepoImage: nexus3.onap.org:10001/onap/refrepo
  refrepoVersion: 1.0-STAGING-latest
